package com.pet.travel.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by xinzhendi-031 on 2018/2/5.
 */
public class PetDatingBean implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.age
     *
     * @mbg.generated
     */
    private Float age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.requirement
     *
     * @mbg.generated
     */
    private String requirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.headurl
     *
     * @mbg.generated
     */
    private String headurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petdating.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table petdating
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.id
     *
     * @return the value of petdating.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.id
     *
     * @param id the value for petdating.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.name
     *
     * @return the value of petdating.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.name
     *
     * @param name the value for petdating.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.type
     *
     * @return the value of petdating.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.type
     *
     * @param type the value for petdating.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.age
     *
     * @return the value of petdating.age
     *
     * @mbg.generated
     */
    public Float getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.age
     *
     * @param age the value for petdating.age
     *
     * @mbg.generated
     */
    public void setAge(Float age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.address
     *
     * @return the value of petdating.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.address
     *
     * @param address the value for petdating.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.sex
     *
     * @return the value of petdating.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.sex
     *
     * @param sex the value for petdating.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.description
     *
     * @return the value of petdating.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.description
     *
     * @param description the value for petdating.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.requirement
     *
     * @return the value of petdating.requirement
     *
     * @mbg.generated
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.requirement
     *
     * @param requirement the value for petdating.requirement
     *
     * @mbg.generated
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.headurl
     *
     * @return the value of petdating.headurl
     *
     * @mbg.generated
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.headurl
     *
     * @param headurl the value for petdating.headurl
     *
     * @mbg.generated
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl == null ? null : headurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.time
     *
     * @return the value of petdating.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.time
     *
     * @param time the value for petdating.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petdating.state
     *
     * @return the value of petdating.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petdating.state
     *
     * @param state the value for petdating.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}