package com.pet.travel.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by xinzhendi-031 on 2018/2/5.
 */
public class PetLookforBean implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.age
     *
     * @mbg.generated
     */
    private Float age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.requirement
     *
     * @mbg.generated
     */
    private String requirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.headurl
     *
     * @mbg.generated
     */
    private String headurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petlookfor.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table petlookfor
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.id
     *
     * @return the value of petlookfor.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.id
     *
     * @param id the value for petlookfor.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.name
     *
     * @return the value of petlookfor.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.name
     *
     * @param name the value for petlookfor.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.type
     *
     * @return the value of petlookfor.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.type
     *
     * @param type the value for petlookfor.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.age
     *
     * @return the value of petlookfor.age
     *
     * @mbg.generated
     */
    public Float getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.age
     *
     * @param age the value for petlookfor.age
     *
     * @mbg.generated
     */
    public void setAge(Float age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.address
     *
     * @return the value of petlookfor.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.address
     *
     * @param address the value for petlookfor.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.sex
     *
     * @return the value of petlookfor.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.sex
     *
     * @param sex the value for petlookfor.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.description
     *
     * @return the value of petlookfor.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.description
     *
     * @param description the value for petlookfor.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.requirement
     *
     * @return the value of petlookfor.requirement
     *
     * @mbg.generated
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.requirement
     *
     * @param requirement the value for petlookfor.requirement
     *
     * @mbg.generated
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.headurl
     *
     * @return the value of petlookfor.headurl
     *
     * @mbg.generated
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.headurl
     *
     * @param headurl the value for petlookfor.headurl
     *
     * @mbg.generated
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl == null ? null : headurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.phone
     *
     * @return the value of petlookfor.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.phone
     *
     * @param phone the value for petlookfor.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.email
     *
     * @return the value of petlookfor.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.email
     *
     * @param email the value for petlookfor.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.time
     *
     * @return the value of petlookfor.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.time
     *
     * @param time the value for petlookfor.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petlookfor.state
     *
     * @return the value of petlookfor.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petlookfor.state
     *
     * @param state the value for petlookfor.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}