package com.pet.travel.bean;

import java.io.Serializable;

/**
 * Created by xinzhendi-031 on 2018/2/5.
 */
public class PetServiceBean  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.pictures
     *
     * @mbg.generated
     */
    private String pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.video
     *
     * @mbg.generated
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petservice.thumb
     *
     * @mbg.generated
     */
    private String thumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table petservice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.id
     *
     * @return the value of petservice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.id
     *
     * @param id the value for petservice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.type
     *
     * @return the value of petservice.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.type
     *
     * @param type the value for petservice.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.name
     *
     * @return the value of petservice.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.name
     *
     * @param name the value for petservice.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.description
     *
     * @return the value of petservice.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.description
     *
     * @param description the value for petservice.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.pictures
     *
     * @return the value of petservice.pictures
     *
     * @mbg.generated
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.pictures
     *
     * @param pictures the value for petservice.pictures
     *
     * @mbg.generated
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.video
     *
     * @return the value of petservice.video
     *
     * @mbg.generated
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.video
     *
     * @param video the value for petservice.video
     *
     * @mbg.generated
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petservice.thumb
     *
     * @return the value of petservice.thumb
     *
     * @mbg.generated
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petservice.thumb
     *
     * @param thumb the value for petservice.thumb
     *
     * @mbg.generated
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }
}